version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - setup_remote_docker
      - run: make build
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: make push
